apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  labels:
    live.app: green
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: green-goreactapp
          servicePort: 8888