apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goreactapp
  name: goreactapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goreactapp
  template:
    metadata:
      labels:
        app: goreactapp
    spec:
      containers:
      - name: goreactapp
        ports:
        - containerPort: 4443
        image: reactgo/goreactapp:0.1.12
        args: ['server', '--mode', 'cyan']