apiVersion: v1
kind: Service
metadata:
  labels:
    app: goreactapp
  name: goreactapp
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 4443
  selector:
    app: goreactapp
  type: ClusterIP